dbt_surf_0:
  outputs:
    prod:
      dbname: SURFALYTICS_DW_AlexG7
      host: surfalytics-prod.postgres.database.azure.com
      pass: Data2024!
      port: 5432
      schema: prod
      threads: 1
      type: postgres
      user: surfalyticsadmin
  target: prod
